version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: appass
      POSTGRES_DB: appdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "5432:5432"

  app:
    build: .
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    # Si quieres sobreescribir DATABASE_URL desde compose:
    environment:
      # Cambia credenciales si no usas .env
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      DATABASE_URL: postgres://appuser:appass@db:5432/appdb
    ports:
      - "4000:4000"
    # en dev es útil montar el código para hot-reload; en prod remueve el volumen
    volumes:
      - ./:/app

volumes:
  pgdata:
